config/routes.rb
Rails.application.routes.draw do
  root "dogs#index"
  post 'dogs/fetch_breed_image', to: 'dogs#fetch_breed_image'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
  end

  def fetch_breed_image
    breed = helpers.format_breed_name(params[:breed])
    result = DogApi.call(breed)

    if result["status"] == "success"
      @image_url = result["message"]
      @breed = params[:breed]
    else
      @image_url = nil
      @breed = params[:breed]
    end

    respond_to do |format|
      format.turbo_stream
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_breed_name(name)
    words_array = name.split(' ')
    reversed_words_array = words_array.reverse
    result = reversed_words_array.join('/')
    result
  end
end

app/views/dogs/fetch_breed_image.turbo_stream.erb
<% if @image_url %>
  <%= turbo_stream.update "breed_frame" do %>
    <h2>Breed: <%= @breed.titleize %></h2>
    <img id="breed-image" src="<%= @image_url %>" alt="Dog breed image" class="img-fluid">
  <% end %>
<% else %>
  <%= turbo_stream.update "breed_frame" do %>
    <h2>Breed: <%= @breed.titleize %></h2>
    <p>Error fetching image for breed: <%= @breed %></p>
    <img id="breed-image" src="" alt="Dog breed image" style="display: none;">
  <% end %>
<% end %>

app/views/dogs/index.html.erb
<div class="row">
  <div class="col-3">
    <%= form_with url: dogs_fetch_breed_image_path, data: { turbo_frame: "breed_frame" }, class: 'form-inline' do %>
      <div>
        <%= label_tag :breed, 'Breed:' %>
        <%= text_field_tag :breed, nil, required: true %>
        <%= submit_tag 'Submit' %>
      </div>
    <% end %>
  </div>
  <div class="col">
    <%= turbo_frame_tag "breed_frame" do %>
      <h2 id="breed-name"></h2>
      <img id="breed-image" src="" alt="Dog breed image" style="display: none;">
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogBreedApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>